import type { Assignment, BannerNotice, ChatMessage, Student, Teacher, TeacherConversation, Tiles, TimeTable } from './types';

export const tilesData: Tiles[] = [
  // Administration
  { category: 'Administration', title: 'Leave', icon: 'CalendarOff', badge: '1', path: '/(Tiles)/LeaveRequest' },
  { category: 'Administration', title: 'Duties', icon: 'ClipboardCheck', badge: '1', path: '/(Tiles)/Duties' },
  { category: 'Administration', title: 'Events', icon: 'CalendarDays', badge: '2', path: '/(Tiles)/Events' },
  { category: 'Administration', title: 'Meetings', icon: 'Users', badge: '1', path: '/(Tiles)/Meetings' },
  // Academics
  { category: 'Academics', title: 'Assignments', icon: 'FileText', badge: '3', path: '/(Tiles)/Assignments' },
  { category: 'Academics', title: 'Subjects', icon: 'BookOpen', badge: '', path: '/(Tiles)/Subjects' },
  { category: 'Academics', title: 'Study Material', icon: 'BookMarked', badge: '', path: '/(Tiles)/StudyMaterial' },
  // Students
  { category: 'students', title: 'Student Profile', icon: 'UserRound', badge: '', path: '/(Tiles)/StudentProfile' },
  { category: 'students', title: 'Attendance', icon: 'CalendarCheck', badge: '', path: '/(Tiles)/MarkAttendance' },
  { category: 'students', title: 'Student Review', icon: 'BarChart3', badge: '', path: '/(Tiles)/StudentReview' },
  // Examination
  { category: 'Examination', title: 'Create Exam', icon: 'FilePlus', badge: '', path: '/(Tiles)/CreateExam' },
  { category: 'Examination', title: 'Upload Marks', icon: 'Upload', badge: '', path: '/(Tiles)/UploadMarks' },
  { category: 'Examination', title: 'Results', icon: 'ChartColumn', badge: '', path: '/(Tiles)/GenerateReport' },
  // Timetable
  { category: 'Timetable', title: 'View Timetable', icon: 'Calendar', badge: '', path: '/(Tiles)/ViewTimetable' },
  { category: 'Timetable', title: 'Manage Timetable', icon: 'CalendarCog', badge: '', path: '/(Tiles)/ManageTimetable' },
  { category: 'Timetable', title: 'Class Routine', icon: 'Clock', badge: '', path: '/(Tiles)/ClassRoutine' },
  { category: 'Timetable', title: 'Room Allocation', icon: 'DoorOpen', badge: '', path: '/(Tiles)/RoomAllocation' },
  // AI Assistant
  { category: 'AI Assistant', title: 'AI Chat Bot', icon: 'Bot', badge: 'AI', path: '/(Tiles)/AIChatBot' },
];

export const timetableData: TimeTable[] = [
  {
    day: 'Monday',
    date: '11 june, 26',
    schedule: [
      { subject: 'Math', startTime: '9:00 AM', endTime: '10:00 AM', Period: '1', class: 'VI C' },
      { subject: 'Science', startTime: '10:00 AM', endTime: '11:00 AM', Period: '2', class: 'VII A ' },
      { subject: 'SST.', startTime: '11:00 AM', endTime: '11:30 AM', Period: '3', class: 'V C' },
      { subject: 'Lang.', startTime: '11:30 AM', endTime: '12:00 PM', Period: '4', class: 'VII B' },
      { subject: 'Comp sci.', startTime: '12:00 PM', endTime: '12:30 PM', Period: '5', class: 'IV C' },
      { subject: 'Play ', startTime: '12:30 PM', endTime: '1:00 PM', Period: '6', class: 'I C' },
    ],
  },
];

export const bannerNotice: BannerNotice[] = [
  {
    title: 'Fee due',
    description: 'Your fee payment is pending . Please complete it by 15 nov .',
    path: '',
    pathname: 'Pay now',
    Color: { Border: '#e88636ff', Button: '#fa7d50ff', Background: '#f9e0ccff' },
  },
  {
    title: 'Result',
    description: 'Your exam result is published',
    path: '',
    pathname: 'view result',
    Color: { Border: '#1084e9ff', Button: '#1d58edff', Background: '#cfdcfdff' },
  },
];

export const mockStudents: Student[] = [
  { id: '1', name: 'Aarav Sharma', rollNo: 'CSE-001', gender: 'male' },
  { id: '2', name: 'Ananya Iyer', rollNo: 'CSE-002', gender: 'female' },
  { id: '3', name: 'Devansh Verma', rollNo: 'CSE-003', gender: 'male' },
  { id: '4', name: 'Ishita Patel', rollNo: 'CSE-004', gender: 'female' },
  { id: '5', name: 'Kabir Mukherjee', rollNo: 'CSE-005', gender: 'male' },
  { id: '6', name: 'Meera Nair', rollNo: 'CSE-006', gender: 'female' },
  { id: '7', name: 'Rohan Gupta', rollNo: 'CSE-007', gender: 'male' },
  { id: '8', name: 'Saanvi Kulkarni', rollNo: 'CSE-008', gender: 'female' },
  { id: '9', name: 'Vihaan Reddy', rollNo: 'CSE-009', gender: 'male' },
  { id: '10', name: 'Zoya Khan', rollNo: 'CSE-010', gender: 'female' },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-1',
    subject: 'Science',
    title: 'Light Reflection and Refraction Lab',
    dueDate: '5th Jul 2026',
    fileType: 'doc',
    fileName: 'science_optics_lab_v2.docx',
    status: 'pending',
    totalMarks: 25,
  },
  {
    id: 'asg-2',
    subject: 'Mathematics',
    title: 'Linear Equations & Matrices Exercise',
    dueDate: '8th Jul 2026',
    fileType: 'pdf',
    fileName: 'matrices_worksheet_ch4.pdf',
    status: 'pending',
    totalMarks: 30,
  },
  {
    id: 'asg-3',
    subject: 'Computer Science',
    title: 'Data Structures: Binary Search Tree',
    dueDate: '10th Jul 2026',
    fileType: 'doc',
    fileName: 'bst_assignment_specs.docx',
    status: 'pending',
    totalMarks: 50,
  },
  {
    id: 'asg-4',
    subject: 'English',
    title: 'Essay on Climate Change Impact',
    dueDate: '12th Jul 2026',
    fileType: 'doc',
    fileName: 'essay_guidelines_topic3.docx',
    status: 'submitted',
    submittedAt: '3rd Jul 2026',
    totalMarks: 20,
  },
  {
    id: 'asg-5',
    subject: 'Science',
    title: 'Acids, Bases and Salts Report',
    dueDate: '15th Jul 2026',
    fileType: 'pdf',
    fileName: 'chemistry_acid_base_practical.pdf',
    status: 'pending',
    totalMarks: 20,
  },
  {
    id: 'asg-6',
    subject: 'Social Studies',
    title: 'Industrial Revolution Timeline & Maps',
    dueDate: '18th Jul 2026',
    fileType: 'ppt',
    fileName: 'industrial_revolution_project.pptx',
    status: 'pending',
    totalMarks: 35,
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: 'tch-1',
    name: 'Dr. Anita Roy',
    title: 'Dr.',
    role: 'Class Teacher • Class VI-B',
    subject: 'Physics & Science',
    department: 'Science',
    avatarText: 'AR',
    avatarBg: '#DBEAFE',
    avatarColor: '#1D4ED8',
    isOnline: true,
    statusText: 'Online',
    room: 'Staff Room 2 (Block A)',
    email: 'anita.roy@operiacampus.edu',
    officeHours: 'Mon–Fri, 02:00 PM – 03:00 PM',
    phone: '+91 98310 44521',
  },
  {
    id: 'tch-2',
    name: 'Mr. Rajesh Sharma',
    title: 'Mr.',
    role: 'HOD Mathematics',
    subject: 'Mathematics',
    department: 'Mathematics',
    avatarText: 'RS',
    avatarBg: '#FFEDD5',
    avatarColor: '#C2410C',
    isOnline: true,
    statusText: 'Online',
    room: 'Room 204 (Math Wing)',
    email: 'rajesh.sharma@operiacampus.edu',
    officeHours: 'Tue & Thu, 11:30 AM – 12:30 PM',
    phone: '+91 98450 11209',
  },
  {
    id: 'tch-3',
    name: 'Mrs. Sunita Verma',
    title: 'Mrs.',
    role: 'Senior Faculty',
    subject: 'Chemistry',
    department: 'Science',
    avatarText: 'SV',
    avatarBg: '#CCFBF1',
    avatarColor: '#0F766E',
    isOnline: false,
    statusText: 'Active 25m ago',
    room: 'Chemistry Lab B',
    email: 'sunita.verma@operiacampus.edu',
    officeHours: 'Mon & Wed, 01:00 PM – 02:00 PM',
    phone: '+91 97120 88412',
  },
  {
    id: 'tch-4',
    name: 'Ms. Neha Verma',
    title: 'Ms.',
    role: 'Subject Teacher',
    subject: 'English Literature',
    department: 'Languages',
    avatarText: 'NV',
    avatarBg: '#F3E8FF',
    avatarColor: '#7E22CE',
    isOnline: false,
    statusText: 'Active 1h ago',
    room: 'Room 105 (Humanities)',
    email: 'neha.verma@operiacampus.edu',
    officeHours: 'Wed & Fri, 03:00 PM – 04:00 PM',
    phone: '+91 98200 66319',
  },
  {
    id: 'tch-5',
    name: 'Mr. Vikram Malhotra',
    title: 'Mr.',
    role: 'Lab Incharge & Faculty',
    subject: 'Computer Science',
    department: 'Technology',
    avatarText: 'VM',
    avatarBg: '#E0F2FE',
    avatarColor: '#0369A1',
    isOnline: true,
    statusText: 'Online',
    room: 'Computer Lab 3 (IT Block)',
    email: 'vikram.malhotra@operiacampus.edu',
    officeHours: 'Mon–Thu, 12:00 PM – 01:00 PM',
    phone: '+91 98111 77340',
  },
  {
    id: 'tch-6',
    name: 'Mr. Tariq Khan',
    title: 'Mr.',
    role: 'Senior Teacher',
    subject: 'Social Science & History',
    department: 'Humanities',
    avatarText: 'TK',
    avatarBg: '#FEF3C7',
    avatarColor: '#B45309',
    isOnline: false,
    statusText: 'Active 3h ago',
    room: 'Room 203 (Heritage Wing)',
    email: 'tariq.khan@operiacampus.edu',
    officeHours: 'Tue & Fri, 02:00 PM – 03:00 PM',
    phone: '+91 98765 22091',
  },
  {
    id: 'tch-7',
    name: 'Coach Devendra Singh',
    title: 'Coach',
    role: 'Sports Coordinator',
    subject: 'Physical Education',
    department: 'Athletics',
    avatarText: 'DS',
    avatarBg: '#DCFCE7',
    avatarColor: '#15803D',
    isOnline: false,
    statusText: 'In Field Practice',
    room: 'Sports Complex Pavillion',
    email: 'devendra.singh@operiacampus.edu',
    officeHours: 'Mon–Sat, 07:30 AM – 08:30 AM',
    phone: '+91 99341 55601',
  },
];

export const mockTeacherConversations: Record<string, TeacherConversation> = {
  'tch-1': {
    teacher: mockTeachers[0],
    unreadCount: 2,
    isPinned: true,
    lastMessage: 'Please make sure to label the ray diagrams clearly before submitting tomorrow.',
    lastMessageTime: '10:42 AM',
    messages: [
      {
        id: 'msg-101',
        sender: 'teacher',
        text: 'Good morning Sourav! Don\'t forget that the Light Reflection practical workbook needs to be submitted this Friday.',
        timestamp: 'Yesterday, 04:15 PM',
        status: 'read',
      },
      {
        id: 'msg-102',
        sender: 'user',
        text: 'Good evening ma\'am! I have completed the observations for the concave mirror experiment. Should I attach the graph sheet directly?',
        timestamp: 'Yesterday, 06:30 PM',
        status: 'read',
      },
      {
        id: 'msg-103',
        sender: 'teacher',
        text: 'Yes, paste the graph neatly on page 14 of your practical journal. I have uploaded the reference chart here:',
        timestamp: 'Yesterday, 08:00 PM',
        status: 'read',
        attachment: {
          name: 'Ray_Optics_Practical_Guidelines.pdf',
          type: 'pdf',
          size: '1.4 MB',
        },
      },
      {
        id: 'msg-104',
        sender: 'user',
        text: 'Thank you ma\'am! I downloaded the PDF and followed the layout.',
        timestamp: '10:15 AM',
        status: 'read',
      },
      {
        id: 'msg-105',
        sender: 'teacher',
        text: 'Please make sure to label the ray diagrams clearly before submitting tomorrow.',
        timestamp: '10:42 AM',
        status: 'delivered',
      },
    ],
  },
  'tch-2': {
    teacher: mockTeachers[1],
    unreadCount: 1,
    isPinned: true,
    lastMessage: 'Solve questions 4 to 9 from Exercise 4.2. We will review them on Thursday.',
    lastMessageTime: '09:15 AM',
    messages: [
      {
        id: 'msg-201',
        sender: 'user',
        text: 'Hello Mr. Sharma, I had a doubt regarding Q7 in the Linear Equations worksheet.',
        timestamp: 'Monday, 05:20 PM',
        status: 'read',
      },
      {
        id: 'msg-202',
        sender: 'teacher',
        text: 'Check if you transposed the variable coefficients with the correct negative sign across the equals boundary.',
        timestamp: 'Monday, 07:10 PM',
        status: 'read',
      },
      {
        id: 'msg-203',
        sender: 'teacher',
        text: 'Solve questions 4 to 9 from Exercise 4.2. We will review them on Thursday.',
        timestamp: '09:15 AM',
        status: 'delivered',
      },
    ],
  },
  'tch-3': {
    teacher: mockTeachers[2],
    unreadCount: 0,
    isPinned: false,
    lastMessage: 'Well done on scoring full marks in the acids and bases test!',
    lastMessageTime: 'Yesterday',
    messages: [
      {
        id: 'msg-301',
        sender: 'teacher',
        text: 'Well done on scoring full marks in the acids and bases test!',
        timestamp: 'Yesterday, 02:40 PM',
        status: 'read',
      },
      {
        id: 'msg-302',
        sender: 'user',
        text: 'Thank you so much, Mrs. Verma! Your revision notes were really helpful.',
        timestamp: 'Yesterday, 03:00 PM',
        status: 'read',
      },
    ],
  },
  'tch-4': {
    teacher: mockTeachers[3],
    unreadCount: 0,
    isPinned: false,
    lastMessage: 'Your draft on "Climate Change" looks promising. Enhance the conclusion.',
    lastMessageTime: 'Jun 8',
    messages: [
      {
        id: 'msg-401',
        sender: 'user',
        text: 'Ma\'am, I submitted my essay draft on the portal. Could you please take a look when free?',
        timestamp: 'Jun 7, 03:10 PM',
        status: 'read',
      },
      {
        id: 'msg-402',
        sender: 'teacher',
        text: 'Your draft on "Climate Change" looks promising. Enhance the conclusion.',
        timestamp: 'Jun 8, 11:20 AM',
        status: 'read',
      },
    ],
  },
  'tch-5': {
    teacher: mockTeachers[4],
    unreadCount: 3,
    isPinned: false,
    lastMessage: 'Remember recursion requires a proper base case or you will get a stack overflow!',
    lastMessageTime: '11:05 AM',
    messages: [
      {
        id: 'msg-501',
        sender: 'user',
        text: 'Sir, my Binary Search Tree inorder traversal is entering an infinite loop in Python.',
        timestamp: '10:30 AM',
        status: 'read',
      },
      {
        id: 'msg-502',
        sender: 'teacher',
        text: 'Check if you are updating current.left or if your root node condition check is returning None correctly.',
        timestamp: '10:48 AM',
        status: 'read',
      },
      {
        id: 'msg-503',
        sender: 'teacher',
        text: 'Remember recursion requires a proper base case or you will get a stack overflow!',
        timestamp: '11:05 AM',
        status: 'delivered',
      },
    ],
  },
  'tch-6': {
    teacher: mockTeachers[5],
    unreadCount: 0,
    isPinned: false,
    lastMessage: 'Yes, you can bring the physical charts for the presentation.',
    lastMessageTime: 'Jun 6',
    messages: [
      {
        id: 'msg-601',
        sender: 'user',
        text: 'Mr. Khan, may we present our Industrial Revolution timeline using chart boards instead of slides?',
        timestamp: 'Jun 6, 01:15 PM',
        status: 'read',
      },
      {
        id: 'msg-602',
        sender: 'teacher',
        text: 'Yes, you can bring the physical charts for the presentation.',
        timestamp: 'Jun 6, 02:00 PM',
        status: 'read',
      },
    ],
  },
  'tch-7': {
    teacher: mockTeachers[6],
    unreadCount: 0,
    isPinned: false,
    lastMessage: 'Basketball trials are scheduled for 06:45 AM this Friday on Court 1.',
    lastMessageTime: 'Jun 5',
    messages: [
      {
        id: 'msg-701',
        sender: 'teacher',
        text: 'Basketball trials are scheduled for 06:45 AM this Friday on Court 1.',
        timestamp: 'Jun 5, 08:30 AM',
        status: 'read',
      },
      {
        id: 'msg-702',
        sender: 'user',
        text: 'Understood Coach! I have my fitness clearance ready.',
        timestamp: 'Jun 5, 09:10 AM',
        status: 'read',
      },
    ],
  },
};
